import * as z from 'zod'

export const formSchema = z.object({
  kategori: z.string().min(1, "Pilih Kategori"),
  kodePemesanan: z.string().min(1, "Kode Pemesanan wajib diisi"),
  instansi: z.string().min(1, "Pilih Instansi"),
  pic: z.string().min(1, "PIC wajib diisi"),
  telp: z.string().optional(),
  email: z.string().optional(),
  nik: z.string().optional(),
  npwp: z.string().optional(),
  alamat: z.string().optional(),
  kota: z.string().optional(),
  provinsi: z.string().optional(),
  quantity: z.any().optional(),
  periodeBerlangganan: z.string().optional(),
  hargaPPN: z.string().optional(),
  tipeTimbangan: z.string().optional(),
  wilayahPengiriman: z.string().optional(),
  berat: z.any().optional(),
  ekspedisi: z.string().optional(),
  nomorResi: z.string().optional(),
  tanggalBarangDiterima: z.string().optional(),
  harga: z.string().optional(),
  ppn11: z.string().optional(),
  ongkirKUT: z.string().optional(),
  hargaPPN11Ongkir: z.string().optional(),
  totalHargaOngkir: z.string().optional(),
  totalHargaJual: z.string().optional(),
  hargaPPN11OngkirReseller: z.string().optional(),
  ppn11Reseller: z.string().optional(),
  ongkirReseller: z.string().optional(),
  hargaPPN11PlusOngkirReseller: z.string().optional(),
  totalHargaOngkirReseller: z.string().optional(),
  nomorSuratPenawaranHarga: z.string().optional(),
  bulanPengirimanSPH: z.string().optional(),
  nomorPOKUT: z.string().optional(),
  tanggalPesananPO: z.string().optional(),
  nomorBAST: z.string().optional(),
  tanggalBAST: z.string().optional(),
  nomorInvoiceKUT: z.string().optional(),
  tanggalInvoiceKUT: z.string().optional(),
  nomorInvoiceInaproc: z.string().optional(),
  nsfp: z.string().optional(),
  tanggalUangMasuk: z.string().optional(),
  jumlahUangMasuk: z.string().optional(),
  rekeningPenerima: z.string().optional(),
  kodeBayar: z.string().optional(),
  keterangan: z.string().optional(),
  nomorPenyampaianDaftarHarga: z.string().optional(),
  nomorFormulirPembelian: z.string().optional(),
  nomorFormulirBerlangganan: z.string().optional(),
  nomorKontrakBerlangganan: z.string().optional(),

  totalHargaReseller: z.string().optional(),
  statusPesanan: z.string().optional(),
  statusOdoo: z.string().optional(),

});
export type FormValues = z.infer<typeof formSchema>;
